In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)
c=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(c)
type(a)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [3]:
print(a.size)
print(b.size)
print(c.size)

5
10
9


In [4]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(3, 3)


In [5]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
int32
int32


In [18]:
np.empty((4,4),dtype=int)  # Create random array element

array([[4128860, 6029375, 3801155, 5570652],
       [6619251, 7536754, 7340124, 7471201],
       [7078005, 4259932, 7340144, 6357060],
       [6357108, 4980828, 6488175, 7077985]])

In [14]:
np.ones((4,3)).transpose()


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.ones((2,3,4), dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [15]:
np.zeros(4)

array([0., 0., 0., 0.])

In [16]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
np.ones((3,3), dtype=str)

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [31]:
np.zeros((3,3), dtype=str)

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [19]:
np.zeros((3,3), dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [20]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array2=np.array([[[1,2,3],[4,5,6]],
                 [[7,8,9],[0,1,7]]]) #this is two 2D's arrays of size of 2x3 ie. [2,2,3] its a 3D array
array2

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 7]]])

In [8]:
array3=np.array([[[1,2],[3,4]],
                [[5,6],[7,8]],
                [[9,0],[0,1]]])
array3
print(array3.shape)

(3, 2, 2)
