In [2]:
import numpy as np

In [6]:
a=np.arange(1,10).reshape((3,3))
b=np.arange(10,19).reshape((3,3))
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [7]:
a+b # simple addition

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [8]:
np.add(a,b)   #another way to do addition

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [9]:
a-b      #simple subtraction

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

In [11]:
np.subtract(a,b)     

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

In [12]:
a*b          # simple multiplication

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [13]:
np.multiply(a,b)    

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [14]:
a/b    # simple division

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ],
       [0.4375    , 0.47058824, 0.5       ]])

In [15]:
np.divide(a,b)

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ],
       [0.4375    , 0.47058824, 0.5       ]])

In [16]:
a@b             # matrix multiplication

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [17]:
a.dot(b)             # another way to represent matrix multiplication

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [20]:
b.max()      # maximum element of all the element present in the matrix

18

In [21]:
b.min()          # minimum element of all the element present in the matrix

10

In [22]:
b.argmax()       # it will tell the maximum element index in the matrix

8

In [23]:
np.sum(a)           # it will do the sum of all the element

45

In [24]:
np.sum(a,axis=0)           # it will do the column addition 

array([12, 15, 18])

In [27]:
np.sum(a,axis=1)          # row addition

array([ 6, 15, 24])

In [28]:
np.mean(a)             # mean of matrix 

5.0

In [29]:
np.sqrt(a)                 # it will do the square root of all elements of the matrix

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [30]:
np.std(a)                # it is calculating the standard deviation of matrix

2.581988897471611

In [31]:
np.log(b)                   # it computing log values

array([[2.30258509, 2.39789527, 2.48490665],
       [2.56494936, 2.63905733, 2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176]])

In [15]:
# my work
a=np.arange(1,10).reshape(3,3)
print(a)
b=a.flatten()
print(b)
c=a.ravel()
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [16]:
import numpy as np

# Original array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Using flatten
flattened = array.flatten()
print("Flattened array:", flattened)

# Using ravel
raveled = np.ravel(array)
print("Raveled array:", raveled)

# Modify the raveled array
raveled[0] = 99

print("Modified raveled array:", raveled)
print("Original array after ravel modification:", array)

# Modify the flattened array
flattened[0] = 88

print("Modified flattened array:", flattened)
print("Original array after flatten modification:", array)


Flattened array: [1 2 3 4 5 6]
Raveled array: [1 2 3 4 5 6]
Modified raveled array: [99  2  3  4  5  6]
Original array after ravel modification: [[99  2  3]
 [ 4  5  6]]
Modified flattened array: [88  2  3  4  5  6]
Original array after flatten modification: [[99  2  3]
 [ 4  5  6]]
