In [1]:
import numpy as np

In [69]:
np.random.random(1)

array([0.47328118])

In [60]:
np.random.random(3)

array([0.47313428, 0.80918054, 0.89577441])

In [61]:
np.random.random((2,2))

array([[0.24661481, 0.03427606],
       [0.90484333, 0.64699034]])

In [31]:
np.random.randint(10)

9

In [38]:
np.random.randint(1,10)

5

In [47]:
np.random.randint(1,10,(3,3))

array([[1, 1, 1],
       [5, 8, 9],
       [5, 2, 3]])

In [48]:
np.random.randint(1,10,(3,2,2))

array([[[2, 1],
        [7, 9]],

       [[6, 2],
        [6, 6]],

       [[6, 4],
        [7, 2]]])

In [75]:
np.random.rand(2)

array([0.0087914 , 0.39056777])

In [70]:
np.random.rand(2,2)

array([[0.42452307, 0.97581095],
       [0.5489715 , 0.85721856]])

In [57]:
np.random.randn(2)

array([ 0.37433644, -0.11904959])

In [76]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.random.choice(a)


3