In [5]:
import numpy as np
a= np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a=np.arange(10,1,-1)
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [7]:
a=np.arange(10,1)
a

array([], dtype=int32)

In [17]:
a=np.arange(1,19)
print(a)
b=a.reshape(6,3)
print(b)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [19]:
a=np.arange(1,10)
b=a.reshape(3,3)
c=b.ravel()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arrayx=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]],
                 [[9,0],[10,11]]])
arrayx

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9,  0],
        [10, 11]]])

In [21]:
arrayx[0]

array([[1, 2],
       [3, 4]])

In [22]:
arrayx[0,0]

array([1, 2])

In [23]:
arrayx[0,0,0]

1

In [25]:
arrayx[0:1]

array([[[1, 2],
        [3, 4]]])

In [35]:
arrayx[0:2,0]

array([[1, 2],
       [5, 6]])

In [27]:
arrayx[1:2]

array([[[5, 6],
        [7, 8]]])

In [28]:
arrayx[:2]

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [29]:
arrayx[0:1,0]

array([[1, 2]])

In [30]:
arrayx[0:1,0,0]

array([1])

In [33]:
arrayx[:2,0,1]

array([2, 6])

In [34]:
arrayx[1: ,1]

array([[ 7,  8],
       [10, 11]])

In [36]:
arrayx[0:2,0,0]

array([1, 5])

In [37]:
arrayx[1: ,1]

array([[ 7,  8],
       [10, 11]])

In [38]:
arrayx[1: ,1,0]

array([ 7, 10])

In [44]:
arrayx[ : ,1]

array([[ 3,  4],
       [ 7,  8],
       [10, 11]])